apiVersion: v1
kind: Service
metadata:
  name: deploy
  namespace: namespace-workflow-1701958946069
spec:
  type: LoadBalancer
  selector:
    app: deploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000